### ISSUE TITLE
Attempt to call function 'get_icon' in base 'null instance' on a null instance

### ISSUE THREAD

**Issue by Adventune** [HungryProton/scatter#188] opened 2024-02-21 14:22 UTC
Version: 4.0
Godot version: 4.2.1

I recently updated from Godot 4.1.3 -> 4.2.1 and since then Modifiers NodePath selection (atleast)  hasn't worked. Logged error:
```
SCRIPT ERROR: Attempt to call function 'get_icon' in base 'null instance' on a null instance.
          at: _create_items_recursive (res://addons/proton_scatter/src/stack/inspector_plugin/ui/modifier/components/parameter_node_selector.gd:67)
```
Removing said line fixes the problem (obiviously) and allows the node selector to function properly.

**Comment by TokisanGames** [comment] 2024-02-21 16:05
Duplicate of #176, fixed weeks ago in 6821b63a120f4c003da7e4d6f9ec28658e8337dc. Update your Scatter.

**Closed as completed** 2024-02-21 16:50 UTC
