### ISSUE TITLE
Scene change crash to desktop

### ISSUE THREAD

**Issue by addmix** [HungryProton/scatter#19] opened 2021-01-04 20:32 UTC
When two scenes have scatter nodes, and in each scene you have the scatter node selected, switching scenes causes a crash to desktop.

**Steps to reproduce**

Open two scenes, each containing a scatter node, in each scene select the scatter node, attempt to switch to the other scene.

**Comment by HungryProton** [comment] 2021-01-04 23:39
Can confirm the bug, probably a recent one as I worked on scene changes last week. I'll look into it

**Comment by HungryProton** [comment] 2021-01-06 15:58
Should be fixed in df88c699c7e2a736b3c5e300161d48d8b0f78aad

This was tricky to debug so if I missed any edge cases, feel free to open this issue again

**Comment by setzer22** [comment] 2021-05-31 17:20
Could there be a regression of this bug? I can reproduce the issue in latest master, but I switched to df88c69 and that works without issues.

I'd be happy to provide more info if necessary :sweat_smile:

**Comment by HungryProton** [comment] 2021-06-02 11:00
Probably a regression, I can reproduce on my end, I'll see what I can do

**Comment by HungryProton** [comment] 2021-06-02 11:32
Should be fixed in 6088d1e4fc18243efcbe58d6798ec0afa5aafe79, but the fix looks weak so let me know if you manage to crash it again.

**Closed** 2021-06-02 16:13 UTC
Labels: bug

**Comment by setzer22** [comment] 2021-06-02 16:56
Seems to be working now. I'll let you know if I get another crash :+1:  Btw, thanks for this amazing addon! :smile:
