### ISSUE TITLE
ScatterItem can delete materials from MeshInstances in .tscn files if they're in Item Path

### ISSUE THREAD

**Issue by DeerTears** [HungryProton/scatter#54] opened 2021-10-04 02:40 UTC
Hi. A quick word of warning, I am having a really hard time getting this bug to happen consistently. I want to give some quick details of what this might be to help tl;dr this currently incomplete issue:
- Using Scatter 2.7.2
- Using an Intel IGP HD Graphics 620: an IGP that doesn't like Godot GLES3 sometimes, but shouldn't affect resource errors like this.
- I am getting ScatterItem to retain materials most of the time if I save my material resources as .tres, rather than leaving them embedded in a .tscn scene that I'm instancing.
- I've only ever had Use Instancing on when using Scatter
- The multimesh inside a ScatterItem shows me the material when it's there, and doesn't have the material when it's gone. I don't know if it's the culprit or just the messenger.
- Here's my scatter modifier stack:
![image](https://user-images.githubusercontent.com/47726614/135785377-06141cd0-bf54-48d4-87d2-bdc58963ad0c.png)

 
I am working on a minimal reproduction project, but this is taking longer than expected, so I want to get this word out now in case others can fill-in with their experience.

I can give any bug-hunters my project file if you want to look for other inconsistencies, DM me on discord: Ember#1765
## Essentially,

If you add a .tscn with a MeshInstance (using a primitive) to a ScatterItem after an unknown series of steps, the material associated with the MeshInstance will be removed from the mesh. If your material is an embedded resource, not saved as a .tres, that material is effectively **deleted**. Here is one example of a scene that's victim to this:

![image](https://user-images.githubusercontent.com/47726614/135784498-76065ced-8f1d-4967-8c4c-7a4d89239367.png)

Thankfully, I saved this material as a .tres and applied it to the child MeshInstance. I didn't realize that Use Instancing was duplicating the first mesh it found rather than instancing the entire scene. From this evidence, I guess I added the material inside the Mesh resource for both MeshInstances.

![image](https://user-images.githubusercontent.com/47726614/135784555-66d05506-f2c2-4515-8a44-6219478b7790.png)

## Retracing my steps

If I save a node like this:
![image](https://user-images.githubusercontent.com/47726614/135778902-14395243-c45a-4b3e-9385-7ed54e84a3e7.png)

And put it in the ScatterItem's Item Path property:

![image](https://user-images.githubusercontent.com/47726614/135778937-4d586fef-afc9-472d-b619-87306f3024e0.png)

Sometimes I can leave the scene and re-enter, only to find that the ScatterItem appears grey and empty, and the .tscn where I saved the Scene (with a Mesh root or Mesh child) has its material removed. I am still trying to fill this gap of the exact steps I took. I recall selecting the MultiMeshInstance node as well.

I can "rebuild", play the game, close the scene and re-open it, quit the project and open it again, switch tabs from 3D to 2D and Script and back, move the path around, add and remove points, it just won't remove on-command.

For a while, playing the game was fine, but resetting the scene using `get_tree().reload_current_scene()` at runtime temporarily made the materials a default white.
![image](https://user-images.githubusercontent.com/47726614/135778980-08f6d640-c335-44bd-a670-74dbdbc8ba4a.png)

Mysteriously, this doesn't work anymore, the material stays. I probably need to start from a new project to try and narrow this down.

I think the magic mix to reproduce this bug is:
- Use embedded materials, not saved
- Place materials inside the mesh resource
- Save a .tscn with a MeshInstance root
- Instance the .tscn with a ScatterItem using Item Path
- Use Distribute Even (? may not matter)
- Use Instancing is on, so it generates a MultiMeshInstance
- Run the scene without directly saving the original .tscn (but keep the default behaviour to save on play) so it's forced to save the Scatter scene **first**, then the original .tscn, then it runs the game.

## Speculation

I wonder if the problem of removing materials happens when Scatter takes control of the original material resource, and changes its material to match something else that's unset. When Scatter does this in tool mode, this becomes a permanent change.

## Other details

I am checking my files with Fork to see how my project changes. I didn't screenshot it, but I had a ShaderMaterial added and embedded in one commit, but it reported to have changed itself to refer an ExtResource that didn't exist elsewhere in the resource.

![image](https://user-images.githubusercontent.com/47726614/135784259-90942916-3b27-4a8e-8a83-34c7a813c08f.png)

Imagine this but there's no ExtResource to point to.

**Comment by HungryProton** [comment] 2021-10-04 08:11
Hi! Thanks for the detailed report!

Version 2.8 doesn't change anything regarding how materials are handled, so it probably won't fix your issue. (But it doesn't hurt to upgrade, especially if you plan to move to Godot 3.4 at some point).


Materials are a pain in Godot, but I think this is probably related to issue #46.

+ Godot doesn't let you edit mesh resources files directly, (when importing an obj for example, you have to create an inherited scene first). 
+ `MultiMeshInstance` doesn't care about this scene and works with the mesh resource directly.
+ Which means, all the materials from the inherited scene are ignored.

The fix was to save a reference to all the materials when the instancing is done the first time, and restore them on `_ready` each time. The issue is, we can't use `Material Override` for this because the mesh may have several surfaces, not just one, so we edit the mesh resource instead. But since the add-on just keeps a reference to the original material, not a duplicate, that's probably what's causing the material to become an ExtResource in the last screenshot. 

This is a tricky issue, but I'll try to come up with a fix soon.

**Comment by HungryProton** [comment] 2021-10-04 12:20
So, it's rather hard to debug since I haven't figured out the exact steps to recreate the issue (it did happen at some point but I don't know what I did exactly). I haven't managed to trigger the bug again after my changes, so maybe it's fixed? Let me know if it happens again.

I've also added an option under the `ScatterItem` node, called `Merge target meshes`.
+ It uses all the meshes from the source scene, rather than just the first one it can find.
+ It still generate a single multimesh but the result is visually identical to what you get when not using instancing.
+ The drawback though is that it creates a brand-new mesh resource, directly stored in the current scene.
  - It's not an issue for small meshes but may or may not cause issues with meshes with a high polycount so it's disabled by default.
  - This option also hides the material issue because of reasons explained in my previous comment
 
It's pushed on the master branch, commit 53cb1fad321024226fe5474d276acc3c219e74a7.
I'll probably make a release soon, but let me know if you still have issues!

**Comment by DeerTears** [comment] 2021-10-04 14:46
Thanks so much for the quick fix! I haven't tried it in full, I'll let you know if the issue comes up again or if it seems totally fixed.

At the very least, the ability to make new resources to protect the instantiated one sounds like a really good work-around. I don't use scatter for high-poly meshes, and my build size is mostly dictated by textures rather than models, so the added filesize shouldn't be an issue for me. After experimenting with the new release I might go back to the old version to try and find something more consistent for reproduction, cause I have a few ideas I haven't tried yet.

**Comment by HungryProton** [comment] 2022-09-05 22:39
Closing due to lack of activity. Feel free to re-open it if the fix above didn't solve it completely.

**Closed by HungryProton** 2022-09-05 22:39 UTC
